package com.blogSpot.backend.Beans;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "USERS")
@NoArgsConstructor
@Getter
@Setter
public class UserBean {

    // makes sure user_id is a PK and will be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int user_id;

    @Column(name = "user_fullname")
    private String name;

    @Column(name = "user_name")
    private String username;

    private String useremail;
    private String user_role;

    // change the column name
    @Column(name = "user_designation")
    private String user_work;

    private String user_password;

}
